import type { AgentProfile } from '../agent-core/run-state';

export const nodeTutorProfile: AgentProfile = {
  id: 'node_tutor',
  agentChannel: 'sub_tutor',
  scope: 'node',
  rolePromptKey: 'subtutor',
  allowedWorkflows: [
    'chat',
    'outline.generateNext',
    'material.generate',
    'feynman_review',
    'topic.generate',
  ],
  defaultTools: [
    'generate_theory',
    'generate_practice',
    'generate_feynman_checklist',
    'generate_mindmap',
    'generate_external_reference_index',
    'read_materials',
    'search_knowledge',
    'search_library',
    'read_source',
    'read_file',
    'list_node_files',
    'search_node_files',
    'list_markdown_headings',
    'read_markdown_section',
    'get_node_progress',
    'record_mistake',
    'append_to_notes',
    'update_file',
    'edit_markdown_file',
    'patch_markdown_file',
    'delete_node_item',
    'rename_node_item',
    'move_node_item',
    'copy_node_item',
    'create_file',
    'web_search',
    'web_fetch',
    'generate_topic',
    'generate_outline',
    'search_videos',
    'write_todos',
    'spawn_subtask',
  ],
  contextPacks: [
    'currentNode',
    'nodeHandoff',
    'nodeOutline',
    'coverageIndex',
    'nodeMaterialsSummary',
    'activeFile',
    'ragSnippets',
    'studentMemory',
    'attachments',
    'searchMode',
    'localeInstruction',
  ],
  policyLayers: [
    'role',
    'guidance',
    'toolRouting',
    'folderPolicy',
    'workflowRouting',
    'searchPolicy',
    'modelIdentity',
    'language',
  ],
  memoryScopes: ['course', 'node', 'session'],
  artifactTypes: ['outline', 'theory_material', 'practice_material', 'answer', 'notes', 'review'],
  verifiers: ['material_structure', 'practiceHasAnswer', 'practiceStructure', 'sourceCitation', 'kcCoverage'],
  loopConfig: {
    maxTurns: 20,
    hardMaxTurns: 80,
    maxTokens: 16_000,
  },
};
