import { describe, expect, it } from 'vitest';
import { repairMermaidFlowchartSafeSubset } from '@shared/mermaid-sanitize';

describe('repairMermaidFlowchartSafeSubset', () => {
  it('repairs nested quoted bracket labels generated by LLMs', () => {
    const input = [
      'flowchart LR',
      '    A["矩阵 A["m×n"]"] -->|"对应元素相加"| SUM["A + B["m×n"]"]',
      '    B["矩阵 B["m×n"]"] -->|"对应元素相加"| SUM',
    ].join('\n');

    const result = repairMermaidFlowchartSafeSubset(input);

    expect(result.changed).toBe(true);
    expect(result.code).toContain('A["矩阵 A(m×n)"]');
    expect(result.code).toContain('SUM["A + B(m×n)"]');
    expect(result.code).toContain('B["矩阵 B(m×n)"]');
    expect(result.code).not.toContain('["m×n"]"]');
  });
});
