import { EditorView } from '@codemirror/view';

export const markdownLiveTheme = EditorView.theme({
  '&': {
    height: '100%',
    color: 'var(--text)',
    backgroundColor: 'var(--app-workspace-bg, var(--surface))',
    fontFamily: 'var(--sans)',
    fontSize: '13.5px',
  },
  '.cm-scroller': {
    fontFamily: 'var(--sans)',
    lineHeight: '1.72',
    overflowX: 'hidden',
    overflowY: 'auto',
  },
  '.cm-content': {
    minHeight: '100%',
    maxWidth: '920px',
    width: '100%',
    margin: '0 auto',
    padding: '24px 34px 36px',
    caretColor: 'var(--accent)',
  },
  '.cm-line': {
    padding: '0',
    minHeight: '1.72em',
    textDecorationLine: 'none',
  },
  '.cm-line *': {
    textDecorationLine: 'none !important',
  },
  '.cm-lineWrapping': {
    wordBreak: 'break-word',
  },
  '.cm-selectionBackground, .cm-content ::selection': {
    backgroundColor: 'color-mix(in srgb, var(--accent) 20%, transparent) !important',
  },
  '&.cm-focused': {
    outline: 'none',
  },
  '.cm-gutters': {
    color: 'var(--text3)',
    backgroundColor: 'var(--app-workspace-bg, var(--surface))',
    borderRight: '1px solid var(--border)',
  },
  '.cm-activeLineGutter': {
    color: 'var(--text2)',
    backgroundColor: 'transparent',
  },
  '.cm-activeLine': {
    backgroundColor: 'transparent',
  },
  '.cm-cursor': {
    borderLeftColor: 'var(--accent)',
  },
  '.md-cm-heading': {
    color: 'var(--text)',
    fontWeight: '720',
    textDecorationLine: 'none !important',
    borderBottom: 'none !important',
  },
  '.md-cm-heading *': {
    textDecorationLine: 'none !important',
    borderBottom: 'none !important',
  },
  '.md-cm-source-marker': {
    color: 'color-mix(in srgb, var(--text3) 58%, transparent) !important',
    opacity: '0.58',
    fontWeight: '400 !important',
    fontStyle: 'normal !important',
    textDecorationLine: 'none !important',
    textDecorationColor: 'transparent !important',
  },
  '.md-cm-h1': {
    fontSize: '22px',
    lineHeight: '1.28',
    fontWeight: '750',
    paddingTop: '0',
    paddingBottom: '10px',
  },
  '.md-cm-h2': {
    fontSize: '18px',
    lineHeight: '1.34',
    fontWeight: '720',
    paddingTop: '14px',
    paddingBottom: '7px',
  },
  '.md-cm-h3': {
    fontSize: '15.5px',
    lineHeight: '1.42',
    fontWeight: '700',
    paddingTop: '10px',
  },
  '.md-cm-h4, .md-cm-h5, .md-cm-h6': {
    fontSize: '14px',
    lineHeight: '1.45',
    fontWeight: '650',
    color: 'var(--text2)',
    paddingTop: '8px',
  },
  '.md-cm-blockquote-line': {
    color: 'var(--text2)',
    borderLeft: '3px solid var(--accent-b)',
    paddingLeft: '12px',
    fontStyle: 'italic',
  },
  '.md-cm-strong': {
    fontWeight: '700',
  },
  '.md-cm-emphasis': {
    fontStyle: 'italic',
  },
  '.md-cm-strikethrough': {
    textDecorationLine: 'line-through !important',
    color: 'var(--text2)',
  },
  '.md-cm-inline-code': {
    fontFamily: 'var(--mono)',
    fontSize: '12px',
    background: 'var(--panel)',
    borderRadius: '3px',
    padding: '1px 5px',
  },
  '.md-cm-link': {
    color: 'var(--accent)',
    textDecorationLine: 'underline !important',
    textDecorationColor: 'var(--accent)',
    textDecorationThickness: '1px',
    textUnderlineOffset: '2px',
    cursor: 'pointer',
  },
  '.md-cm-link *': {
    color: 'var(--accent)',
    textDecorationLine: 'underline !important',
    textDecorationColor: 'var(--accent)',
    textDecorationThickness: '1px',
    textUnderlineOffset: '2px',
  },
  '.md-cm-link:hover': {
    color: 'color-mix(in srgb, var(--accent) 86%, var(--text))',
    textDecorationLine: 'underline !important',
    textDecorationThickness: '1.5px',
  },
  '.md-cm-block-widget': {
    maxWidth: '100%',
    margin: '0',
    padding: '8px 0',
    boxSizing: 'border-box',
  },
  '.md-cm-code-block': {
    position: 'relative',
    background: 'color-mix(in srgb, var(--panel) 68%, transparent)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--r)',
    overflow: 'hidden',
    transition: 'border-color 120ms ease, box-shadow 120ms ease',
  },
  '.md-cm-code-block pre': {
    margin: '0',
    padding: '12px 14px',
    overflowX: 'auto',
  },
  '.md-cm-code-block code': {
    fontFamily: 'var(--mono)',
    fontSize: '12px',
    lineHeight: '1.65',
    whiteSpace: 'pre',
  },
  '.md-cm-code-editor': {
    display: 'block',
    width: '100%',
    minHeight: '42px',
    margin: '0',
    padding: '12px 14px',
    border: 'none',
    outline: 'none',
    resize: 'none',
    overflow: 'hidden',
    boxSizing: 'border-box',
    color: 'var(--text)',
    background: 'transparent',
    fontFamily: 'var(--mono)',
    fontSize: '12px',
    lineHeight: '1.65',
    whiteSpace: 'pre',
  },
  '.md-cm-code-block:focus-within': {
    borderColor: 'color-mix(in srgb, var(--accent) 42%, var(--border))',
    boxShadow: '0 0 0 1px color-mix(in srgb, var(--accent) 18%, transparent)',
  },
  '.md-cm-code-label': {
    padding: '5px 10px',
    borderBottom: '1px solid var(--border)',
    color: 'var(--text3)',
    fontFamily: 'var(--mono)',
    fontSize: '11px',
    background: 'color-mix(in srgb, var(--surface2) 36%, transparent)',
  },
  '.md-cm-math': {
    cursor: 'text',
  },
  '.md-cm-inline-math': {
    display: 'inline-flex',
    alignItems: 'baseline',
    maxWidth: '100%',
    borderRadius: '3px',
    verticalAlign: 'baseline',
    transition: 'color 120ms ease, text-shadow 120ms ease',
  },
  '.md-cm-block-math': {
    overflowX: 'auto',
    overflowY: 'hidden',
    padding: '3px 0',
    textAlign: 'center',
    borderRadius: 'var(--r)',
    transition: 'box-shadow 120ms ease',
  },
  '.md-cm-inline-math:hover': {
    color: 'color-mix(in srgb, var(--text) 88%, var(--accent))',
    textShadow: '0 0 0 color-mix(in srgb, var(--accent) 18%, transparent)',
  },
  '.md-cm-inline-math-editor': {
    minWidth: '8ch',
    maxWidth: '48vw',
    padding: '0 3px',
    border: 'none',
    borderBottom: '1px solid color-mix(in srgb, var(--accent) 46%, transparent)',
    outline: 'none',
    color: 'var(--text)',
    background: 'transparent',
    fontFamily: 'var(--mono)',
    fontSize: '12px',
    lineHeight: '1.45',
  },
  '.md-cm-block-math:hover': {
    boxShadow: 'inset 0 -1px color-mix(in srgb, var(--accent) 30%, transparent)',
  },
  '.md-cm-block-math-editor': {
    display: 'block',
    width: '100%',
    minHeight: '52px',
    padding: '8px 10px',
    border: '1px solid color-mix(in srgb, var(--accent) 28%, var(--border))',
    borderRadius: 'var(--r)',
    outline: 'none',
    resize: 'none',
    overflow: 'hidden',
    boxSizing: 'border-box',
    color: 'var(--text)',
    background: 'color-mix(in srgb, var(--surface) 54%, transparent)',
    fontFamily: 'var(--mono)',
    fontSize: '12px',
    lineHeight: '1.55',
  },
  '.md-cm-code-block:hover': {
    borderColor: 'color-mix(in srgb, var(--accent) 32%, var(--border))',
    boxShadow: '0 0 0 1px color-mix(in srgb, var(--accent) 12%, transparent)',
  },
  '.md-cm-image-widget': {
    display: 'inline-flex',
    maxWidth: '100%',
    verticalAlign: 'middle',
    borderRadius: '4px',
    cursor: 'text',
  },
  '.md-cm-image-widget img': {
    display: 'block',
    maxWidth: '100%',
    maxHeight: '520px',
    height: 'auto',
    borderRadius: '4px',
    boxShadow: '0 1px 6px rgba(0,0,0,0.10)',
    transition: 'box-shadow 120ms ease',
  },
  '.md-cm-image-widget:hover img': {
    boxShadow: '0 1px 8px rgba(0,0,0,0.13), 0 0 0 1px color-mix(in srgb, var(--accent) 18%, transparent)',
  },
  '.md-cm-image-widget.is-missing': {
    color: 'var(--text3)',
    border: '1px dashed var(--border2)',
    padding: '2px 6px',
    fontSize: '12px',
  },
  '.md-cm-table-widget': {
    overflowX: 'auto',
    cursor: 'text',
    borderRadius: '4px',
  },
  '.md-cm-table-widget table': {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '12.5px',
    background: 'color-mix(in srgb, var(--surface) 64%, transparent)',
    transition: 'box-shadow 120ms ease, border-color 120ms ease',
  },
  '.md-cm-table-widget th, .md-cm-table-widget td': {
    border: '1px solid var(--border)',
    padding: '6px 9px',
    textAlign: 'left',
    verticalAlign: 'top',
  },
  '.md-cm-table-widget th': {
    background: 'color-mix(in srgb, var(--surface2) 52%, transparent)',
    fontWeight: '600',
  },
  '.md-cm-table-widget:hover table': {
    boxShadow: '0 0 0 1px color-mix(in srgb, var(--accent) 16%, transparent)',
  },
  '.md-cm-table-cell': {
    cursor: 'text',
    transition: 'box-shadow 120ms ease',
  },
  '.md-cm-table-cell:hover': {
    boxShadow: 'inset 0 0 0 1px color-mix(in srgb, var(--accent) 18%, transparent)',
  },
  '.md-cm-table-cell:focus-within': {
    boxShadow: 'inset 0 0 0 1px color-mix(in srgb, var(--accent) 38%, transparent)',
  },
  '.md-cm-table-empty-cell': {
    color: 'color-mix(in srgb, var(--text3) 62%, transparent)',
    fontStyle: 'italic',
  },
  '.md-cm-table-cell-editor': {
    display: 'block',
    width: '100%',
    minWidth: '12ch',
    minHeight: '24px',
    margin: '0',
    padding: '0',
    border: 'none',
    outline: 'none',
    resize: 'vertical',
    boxSizing: 'border-box',
    color: 'var(--text)',
    background: 'transparent',
    font: 'inherit',
    lineHeight: 'inherit',
  },
  '.md-cm-table-widget a': {
    color: 'var(--accent)',
    textDecorationLine: 'underline',
    textDecorationColor: 'var(--accent)',
    textDecorationThickness: '1px',
    textUnderlineOffset: '2px',
    cursor: 'pointer',
  },
  '.md-cm-hr-widget': {
    cursor: 'text',
  },
  '.md-cm-hr-widget hr': {
    border: 'none',
    borderTop: '1px solid var(--border)',
    transition: 'border-color 120ms ease',
  },
  '.md-cm-hr-widget:hover hr': {
    borderTopColor: 'color-mix(in srgb, var(--accent) 26%, var(--border))',
  },
  '.md-cm-task-checkbox': {
    width: '13px',
    height: '13px',
    margin: '0 4px 0 0',
    transform: 'translateY(1px)',
    accentColor: 'var(--accent)',
    cursor: 'pointer',
  },
  '.md-cm-mermaid': {
    width: '100%',
    maxWidth: '100%',
    minWidth: '0',
    overflow: 'hidden',
    cursor: 'text',
    position: 'relative',
    background: 'color-mix(in srgb, var(--surface) 46%, transparent)',
    borderRadius: '4px',
    boxSizing: 'border-box',
    transition: 'box-shadow 120ms ease, border-color 120ms ease',
  },
  '.md-cm-mermaid-stage': {
    width: '100%',
    maxWidth: '100%',
    minWidth: '0',
    minHeight: 'var(--md-cm-mermaid-height, 260px)',
    height: 'auto',
    display: 'grid',
    placeItems: 'center',
    overflow: 'hidden',
    boxSizing: 'border-box',
    padding: '14px 18px',
  },
  '.md-cm-mermaid-stage.is-loading': {
    minHeight: 'var(--md-cm-mermaid-height, 260px)',
    color: 'var(--text3)',
    fontSize: '12px',
  },
  '.md-cm-mermaid-render-host': {
    position: 'absolute',
    left: '0',
    top: '0',
    width: '100%',
    maxWidth: '100%',
    height: '0',
    overflow: 'hidden',
    visibility: 'hidden',
    pointerEvents: 'none',
    contain: 'layout paint style',
  },
  '.md-cm-widget-toolbar': {
    position: 'absolute',
    top: '8px',
    right: '10px',
    zIndex: '2',
    display: 'flex',
    gap: '6px',
    opacity: '0',
    pointerEvents: 'none',
    transform: 'translateY(-2px)',
    transition: 'opacity 120ms ease, transform 120ms ease',
  },
  '.md-cm-widget-button': {
    border: '1px solid color-mix(in srgb, var(--border) 72%, transparent)',
    borderRadius: '999px',
    padding: '2px 8px',
    color: 'var(--text2)',
    background: 'color-mix(in srgb, var(--surface) 76%, transparent)',
    boxShadow: '0 1px 4px rgba(0,0,0,0.08)',
    fontSize: '11px',
    lineHeight: '1.45',
    cursor: 'pointer',
  },
  '.md-cm-widget-button:hover': {
    color: 'var(--text)',
    borderColor: 'color-mix(in srgb, var(--accent) 34%, var(--border))',
  },
  '.md-cm-mermaid:hover': {
    boxShadow: '0 0 0 1px color-mix(in srgb, var(--accent) 14%, transparent)',
  },
  '.md-cm-mermaid:hover .md-cm-widget-toolbar, .md-cm-widget-toolbar:focus-within': {
    opacity: '0.86',
    pointerEvents: 'auto',
    transform: 'translateY(0)',
  },
  '.md-cm-mermaid-editor': {
    marginTop: '10px',
    padding: '10px',
    borderTop: '1px solid color-mix(in srgb, var(--border) 72%, transparent)',
    background: 'color-mix(in srgb, var(--surface) 42%, transparent)',
  },
  '.md-cm-mermaid-source-editor': {
    display: 'block',
    width: '100%',
    minHeight: '96px',
    maxHeight: '46vh',
    border: 'none',
    outline: 'none',
    resize: 'vertical',
    color: 'var(--text)',
    background: 'transparent',
    fontFamily: 'var(--mono)',
    fontSize: '12px',
    lineHeight: '1.6',
    whiteSpace: 'pre',
  },
  '.md-cm-widget-actions': {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '6px',
    marginTop: '8px',
  },
  '.md-cm-mermaid svg': {
    display: 'block',
    width: 'min(100%, var(--md-cm-mermaid-width, 860px)) !important',
    maxWidth: 'min(100%, var(--md-cm-mermaid-width, 860px)) !important',
    minWidth: '0 !important',
    height: 'auto !important',
    maxHeight: 'none !important',
    margin: '0 auto',
    overflow: 'visible',
  },
  '.katex-display': {
    margin: '0',
  },
  '.katex': {
    fontSize: '1em',
  },
  '.katex-error': {
    color: 'var(--accent)',
    whiteSpace: 'normal',
  },
});
